dist: xenial

jdk:
  - openjdk8
  - openjdk11

language: scala
scala:
  - 2.12.7

script:
  - sbt clean compile

.deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: openapi.*.yaml
  skip_cleanup: true
  on:
    tags: true